### ISSUE TITLE
npm run build failed TypeScript error

### ISSUE THREAD

**Issue by adilirfan-335** [1azy-guy/CoolSwap-interface#3]
Creating an optimized production build...
Failed to compile.

Uniswap-UI-fork-master/node_modules/@types/react-router/index.d.ts
TypeScript error in Uniswap-UI-fork-master/node_modules/@types/react-router/index.d.ts(149,100):
Type expected.  TS1110

    147 | ): match<Params> | null;
    148 |
  > 149 | export type ExtractRouteOptionalParam<T extends string, U = string | number | boolean> = T extends `${infer Param}?`
        |                                                                                                    ^
    150 |     ? { [k in Param]?: U }
    151 |     : T extends `${infer Param}*`
    152 |     ? { [k in Param]?: U }

**Comment by 0x0Ayush** [comment]
How have you found the solution of this?
